#!/usr/bin/env bash
# =============================================================================
# ASR Solver - Probe Phase
# =============================================================================
# Runtime-probes top candidates to validate compatibility.
# =============================================================================
# This script is sourced by run.sh which sets:
#   ASR_SOLVER_DIR, ARTIFACTS_DIR, RAW_DIR, VENV_DIR
# =============================================================================

set -euo pipefail

# Script location (for reference)
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"

# Source common utilities
# shellcheck source=common.sh
source "${ASR_SOLVER_DIR}/lib/common.sh"

# Use paths from run.sh environment
LOGS_DIR="${ARTIFACTS_DIR}/logs"
mkdir -p "$LOGS_DIR"
VENV_DIR="${ASR_SOLVER_DIR}/.solver-venv"

log_info "Starting probe phase..."
log_info "Artifacts directory: $ARTIFACTS_DIR"

# =============================================================================
# Build Probe Docker Images
# =============================================================================

build_probe_images() {
    log_info "Building probe Docker images..."
    
    local cuda_families="$CUDA_FAMILIES"
    read -ra families <<< "$cuda_families"
    
    for family in "${families[@]}"; do
        local image_name
        eval "image_name=\"\${CUDA_IMAGE_${family}}\""
        
        log_info "Building core probe image for $family..."
        docker build \
            --build-arg BASE_IMAGE="$image_name" \
            -t "asr-probe-core-${family}" \
            -f "${ASR_SOLVER_DIR}/docker/Dockerfile.core-probe" \
            "${ASR_SOLVER_DIR}" > /dev/null 2>&1 || true
        
        log_info "Building full probe image for $family..."
        docker build \
            --build-arg BASE_IMAGE="$image_name" \
            -t "asr-probe-full-${family}" \
            -f "${ASR_SOLVER_DIR}/docker/Dockerfile.full-probe" \
            "${ASR_SOLVER_DIR}" > /dev/null 2>&1 || true
    done
    
    log_info "Probe images built successfully"
}

# =============================================================================
# Probe a Single Candidate
# =============================================================================

probe_candidate() {
    local rank="$1"
    local candidate_json="$2"
    
    local cuda_family
    local ctranslate2_version
    local faster_whisper_version
    local torch_version
    local torchaudio_version
    local whisperx_version
    
    # Parse candidate JSON
    cuda_family=$(echo "$candidate_json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('cuda_family',''))")
    ctranslate2_version=$(echo "$candidate_json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('ctranslate2',''))")
    faster_whisper_version=$(echo "$candidate_json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('faster_whisper',''))")
    torch_version=$(echo "$candidate_json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('torch',''))")
    torchaudio_version=$(echo "$candidate_json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('torchaudio',''))")
    whisperx_version=$(echo "$candidate_json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('whisperx',''))")
    
    local log_file="${LOGS_DIR}/core-rank${rank}.log"
    local full_log_file="${LOGS_DIR}/full-rank${rank}.log"
    
    log_info "Probing candidate $rank: $cuda_family / $torch_version"
    
    # Generate constraints file
    local constraints_file="${ARTIFACTS_DIR}/constraints-rank${rank}.txt"
    cat > "$constraints_file" << EOF
# Constraints for candidate rank $rank
# Generated by ASR Solver
EOF
    
    # Get PyTorch index URL
    local pytorch_index
    eval "pytorch_index=\"\${PYTORCH_INDEX_${cuda_family}}\""
    
    # Run core probe
    log_info "Running core probe..."
    "$VENV_DIR/bin/python" "${ASR_SOLVER_DIR}/container-scripts/core_probe.py" \
        --cuda-family "$cuda_family" \
        --ctranslate2 "$ctranslate2_version" \
        --faster-whisper "$faster_whisper_version" \
        --torch "$torch_version" \
        --torchaudio "$torchaudio_version" \
        --constraints "$constraints_file" \
        --pytorch-index "$pytorch_index" \
        --log-file "$log_file" \
        --artifacts-dir "$ARTIFACTS_DIR"
    
    local core_status=$?
    
    # Run full probe if core passed
    local full_status=0
    if [[ $core_status -eq 0 ]]; then
        log_info "Running full probe..."
        "$VENV_DIR/bin/python" "${ASR_SOLVER_DIR}/container-scripts/full_probe.py" \
            --cuda-family "$cuda_family" \
            --ctranslate2 "$ctranslate2_version" \
            --faster-whisper "$faster_whisper_version" \
            --torch "$torch_version" \
            --torchaudio "$torchaudio_version" \
            --whisperx "$whisperx_version" \
            --constraints "$constraints_file" \
            --pytorch-index "$pytorch_index" \
            --log-file "$full_log_file" \
            --artifacts-dir "$ARTIFACTS_DIR"
        full_status=$?
    fi
    
    # Return probe result
    if [[ $core_status -eq 0 ]]; then
        echo "pass"
    else
        echo "fail"
    fi
}

# =============================================================================
# Main Probe Pipeline
# =============================================================================

run_probes() {
    local top_candidates="${TOP_CANDIDATES:-3}"
    
    log_info "Probing top $top_candidates candidates..."
    
    # Read candidate stacks
    local candidates_file="${ARTIFACTS_DIR}/candidate-stacks.json"
    
    if [[ ! -f "$candidates_file" ]]; then
        error_exit "Candidate stacks not found. Run solve first."
    fi
    
    # Build probe images
    build_probe_images
    
    # Initialize results array
    local results="[]"
    
    # Probe each candidate (up to top_candidates)
    local rank=1
    while IFS= read -r candidate; do
        if [[ $rank -gt $top_candidates ]]; then
            break
        fi
        
        local result
        result=$(probe_candidate "$rank" "$candidate")
        
        # Add result to results array
        results=$(echo "$results" | python3 -c "
import json,sys
data = json.load(sys.stdin)
data.append({
    'candidate_rank': $rank,
    'status': '$result'
})
print(json.dumps(data))
")
        
        rank=$((rank + 1))
    done < <(python3 -c "
import json
with open('$candidates_file') as f:
    data = json.load(f)
for c in data.get('candidates', [])[:$top_candidates]:
    print(json.dumps(c))
")
    
    # Save results
    echo "$results" > "${ARTIFACTS_DIR}/probe-results.json"
    
    log_info "Probe results saved to ${ARTIFACTS_DIR}/probe-results.json"
}

main() {
    echo "========================================"
    echo "Probe Phase"
    echo "========================================"
    
    run_probes
    
    echo ""
    echo "Probe complete!"
    echo "Results: ${ARTIFACTS_DIR}/probe-results.json"
    echo "Logs: $LOGS_DIR"
}

main
