#!/usr/bin/env bash
# =============================================================================
# ASR Solver - Probe Phase
# =============================================================================
# Runtime-probes top candidates to validate compatibility.
# =============================================================================
# This script is sourced by run.sh which sets:
#   ASR_SOLVER_DIR, ARTIFACTS_DIR, RAW_DIR, VENV_DIR
# =============================================================================

set -euo pipefail

# Script location (for reference)
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"

# Source common utilities
# shellcheck source=common.sh
source "${ASR_SOLVER_DIR}/lib/common.sh"

# Use paths from run.sh environment
LOGS_DIR="${ARTIFACTS_DIR}/logs"
mkdir -p "$LOGS_DIR"

log_info "Starting probe phase..."
log_info "Artifacts directory: $ARTIFACTS_DIR"

# =============================================================================
# Build Probe Docker Images
# =============================================================================

build_probe_images() {
    log_info "Building probe Docker images..."
    
    local cuda_families="$CUDA_FAMILIES"
    read -ra families <<< "$cuda_families"
    
    for family in "${families[@]}"; do
        local image_name
        eval "image_name=\"\${CUDA_IMAGE_${family}}\""
        
        log_info "Building core probe image for $family..."
        if ! docker build \
            --build-arg BASE_IMAGE="$image_name" \
            -t "asr-probe-core-${family}" \
            -f "${ASR_SOLVER_DIR}/docker/Dockerfile.core-probe" \
            "${ASR_SOLVER_DIR}" 2>&1; then
            log_warn "Failed to build core probe image for $family"
        fi
        
        log_info "Building full probe image for $family..."
        if ! docker build \
            --build-arg BASE_IMAGE="$image_name" \
            -t "asr-probe-full-${family}" \
            -f "${ASR_SOLVER_DIR}/docker/Dockerfile.full-probe" \
            "${ASR_SOLVER_DIR}" 2>&1; then
            log_warn "Failed to build full probe image for $family"
        fi
    done
    
    log_info "Probe images built successfully"
}

# =============================================================================
# Probe a Single Candidate
# =============================================================================

probe_candidate() {
    local rank="$1"
    local candidate_json="$2"
    
    local cuda_family
    local ctranslate2_version
    local faster_whisper_version
    local torch_version
    local torchaudio_version
    local whisperx_version
    
    # Parse candidate JSON
    cuda_family=$(echo "$candidate_json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('candidate', {}).get('cuda_family',''))")
    ctranslate2_version=$(echo "$candidate_json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('candidate', {}).get('ctranslate2',''))")
    faster_whisper_version=$(echo "$candidate_json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('candidate', {}).get('faster_whisper',''))")
    torch_version=$(echo "$candidate_json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('candidate', {}).get('torch',''))")
    torchaudio_version=$(echo "$candidate_json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('candidate', {}).get('torchaudio',''))")
    whisperx_version=$(echo "$candidate_json" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('candidate', {}).get('whisperx',''))")
    
    local log_file="${LOGS_DIR}/core-rank${rank}.log"
    local full_log_file="${LOGS_DIR}/full-rank${rank}.log"
    
    log_info "Probing candidate $rank: $cuda_family / $torch_version"
    
    # Generate constraints file
    local constraints_file="${ARTIFACTS_DIR}/constraints-rank${rank}.txt"
    cat > "$constraints_file" << EOF
# Constraints for candidate rank $rank
# Generated by ASR Solver
EOF
    
    # Get PyTorch index URL
    local pytorch_index=""
    if [[ -n "$cuda_family" ]]; then
        eval "pytorch_index=\"\${PYTORCH_INDEX_${cuda_family}:-}\""
    fi
    
    # Run core probe via Docker (redirect output to log file)
    log_info "Running core probe..."
    local artifacts_relative="${ARTIFACTS_DIR#$ASR_SOLVER_DIR/}"
    
    # Verify Docker image exists before running
    if ! docker images --format "{{.Repository}}:{{.Tag}}" | grep -q "^asr-probe-core-${cuda_family}:"; then
        log_error "Docker image asr-probe-core-${cuda_family} not found"
        printf '%s' "fail"
        return
    fi

    if ! docker run --rm \
        -v "${ASR_SOLVER_DIR}:/solver" \
        -w /solver \
        "asr-probe-core-${cuda_family}" \
        python3 /solver/container-scripts/core_probe.py \
            --cuda-family "$cuda_family" \
            --ctranslate2 "$ctranslate2_version" \
            --faster-whisper "$faster_whisper_version" \
            --torch "$torch_version" \
            --torchaudio "$torchaudio_version" \
            --constraints "/solver/${artifacts_relative}/constraints-rank${rank}.txt" \
            --pytorch-index "$pytorch_index" \
            --log-file "/solver/${artifacts_relative}/logs/core-rank${rank}.log" \
            --artifacts-dir "/solver/${artifacts_relative}" > "${LOGS_DIR}/core-rank${rank}.log" 2>&1; then
        log_warn "Core probe failed for candidate $rank"
        printf '%s' "fail"
        return
    fi
    
    # Run full probe if core passed
    local full_status=0
    if [[ -f "${ARTIFACTS_DIR}/logs/core-rank${rank}.log" ]] && grep -q "Core probe complete" "${ARTIFACTS_DIR}/logs/core-rank${rank}.log"; then
        log_info "Running full probe..."
        
        # Verify Docker image exists before running
        if ! docker images --format "{{.Repository}}:{{.Tag}}" | grep -q "^asr-probe-full-${cuda_family}:"; then
            log_error "Docker image asr-probe-full-${cuda_family} not found"
            printf '%s' "fail"
            return
        fi

        if ! docker run --rm \
            -v "${ASR_SOLVER_DIR}:/solver" \
            -w /solver \
            "asr-probe-full-${cuda_family}" \
            python3 /solver/container-scripts/full_probe.py \
                --cuda-family "$cuda_family" \
                --ctranslate2 "$ctranslate2_version" \
                --faster-whisper "$faster_whisper_version" \
                --torch "$torch_version" \
                --torchaudio "$torchaudio_version" \
                --whisperx "$whisperx_version" \
                --constraints "/solver/${artifacts_relative}/constraints-rank${rank}.txt" \
                --pytorch-index "$pytorch_index" \
                --log-file "/solver/${artifacts_relative}/logs/full-rank${rank}.log" \
                --artifacts-dir "/solver/${artifacts_relative}" > "${LOGS_DIR}/full-rank${rank}.log" 2>&1; then
            log_warn "Full probe failed for candidate $rank"
            printf '%s' "fail"
            return
        fi
        
        if [[ -f "${ARTIFACTS_DIR}/logs/full-rank${rank}.log" ]] && grep -q "Full probe complete" "${ARTIFACTS_DIR}/logs/full-rank${rank}.log"; then
            printf '%s' "pass"
            return
        fi
    fi
    
    printf '%s' "fail"
}

# =============================================================================
# Main Probe Pipeline
# =============================================================================

run_probes() {
    local top_candidates="${TOP_CANDIDATES:-3}"
    
    log_info "Probing top $top_candidates candidates..."
    
    # Read candidate stacks
    local candidates_file="${ARTIFACTS_DIR}/candidate-stacks.json"
    
    if [[ ! -f "$candidates_file" ]]; then
        error_exit "Candidate stacks not found. Run solve first."
    fi
    
    # Build probe images
    build_probe_images
    
    # Initialize results array
    local results="[]"
    
    # Probe each candidate (up to top_candidates)
    local rank=1
    while IFS= read -r candidate; do
        if [[ $rank -gt $top_candidates ]]; then
            break
        fi
        
        local result
        result=$(probe_candidate "$rank" "$candidate" | tr '\n' ' ')
        
        # Add result to results array using Python with proper escaping
        # Use a temporary file to avoid shell escaping issues
        local temp_file="${ARTIFACTS_DIR}/.temp_result_${rank}.json"
        python3 -c "
import json, sys
data = json.loads(sys.argv[1])
data.append({
    'candidate_rank': $rank,
    'status': sys.argv[2]
})
with open('${temp_file}', 'w') as f:
    json.dump(data, f)
" "$results" "$result"
        
        # Read back the temp file
        results=$(cat "$temp_file")
        rm -f "$temp_file"
        
        rank=$((rank + 1))
    done < <(python3 -c "
import json
with open('$candidates_file') as f:
    data = json.load(f)
for c in data.get('candidates', [])[:$top_candidates]:
    print(json.dumps(c))
")
    
    # Save results as a dictionary with 'results' key
    python3 -c "
import json
data = json.loads('$results')
with open('${ARTIFACTS_DIR}/probe-results.json', 'w') as f:
    json.dump({'results': data}, f, indent=2)
"
    
    log_info "Probe results saved to ${ARTIFACTS_DIR}/probe-results.json"
}

main() {
    echo "========================================"
    echo "Probe Phase"
    echo "========================================"
    
    run_probes
    
    echo ""
    echo "Probe complete!"
    echo "Results: ${ARTIFACTS_DIR}/probe-results.json"
    echo "Logs: $LOGS_DIR"
}

main
